#define RAYTRACE_RT_SLOT 0
#define BVH_SLOT 2
#define OTHER_RESOURCES_START 4
#define NUM_OF_TEXTURES 200
#define IMGUI_START OTHER_RESOURCES_START + NUM_OF_TEXTURES

#define NUM_THREADS 4
#define FIRST_THREAD 0
#define FIRST_DRAW_THREAD 1
#define LAST_DRAW_THREAD (NUM_THREADS-2)
#define LAST_THREAD (NUM_THREADS-1)
#define NUM_DRAW_THREAD (NUM_THREADS - 2)